MATH_EXAMS = {
    "grade3-1": {
        "id": "grade3-1",
        "title": "수와 연산 3-1",
        "grade": "초등 3-1",
        "source_file": "수와 연산 3-1(완성본).hwp",
        "description": "덧셈과 뺄셈 중심의 객관식 시험",
        "workbook": {
            "page_count": 109,
            "static_directory": "math_workbooks/grade3-1",
        },
        "questions": [
            {
                "id": "g3_01",
                "source": "6페이지 01",
                "section": "1.1.1 받아올림이 없는 세 자리 수의 덧셈",
                "type": "choice",
                "prompt": "313과 261만큼 놓은 수 모형이 모두 몇 개인지 구하려고 합니다. 백 모형, 십 모형, 일 모형의 개수를 차례대로 고르시오.",
                "choices": [
                    {"value": "1", "label": "①", "text": "4, 7, 4"},
                    {"value": "2", "label": "②", "text": "5, 6, 3"},
                    {"value": "3", "label": "③", "text": "5, 7, 4"},
                ],
                "answer": "3",
                "answer_display": "③ 5, 7, 4",
            },
            {
                "id": "g3_02",
                "source": "6페이지 02",
                "section": "1.1.1 받아올림이 없는 세 자리 수의 덧셈",
                "type": "choice",
                "prompt": "수 모형을 보고 □ 안에 알맞은 수를 구하시오.",
                "latex": r"142 + 354 = \Box",
                "answer": "496",
                "accepted": ["496"],
                "answer_display": "496",
            },
            {
                "id": "g3_03",
                "source": "6페이지 03",
                "section": "1.1.1 받아올림이 없는 세 자리 수의 덧셈",
                "type": "choice",
                "prompt": "342+327을 계산할 때 □ 안에 알맞은 수를 차례대로 고르시오.",
                "body": ["2+7=9", "40+20=□", "300+300=600", "342+327=□"],
                "choices": [
                    {"value": "1", "label": "①", "text": "50, 659"},
                    {"value": "2", "label": "②", "text": "60, 669"},
                    {"value": "3", "label": "③", "text": "80, 689"},
                ],
                "answer": "2",
                "answer_display": "② 60, 669",
            },
            {
                "id": "g3_04",
                "source": "6페이지 04",
                "section": "1.1.1 받아올림이 없는 세 자리 수의 덧셈",
                "type": "choice",
                "prompt": "세로셈에서 □ 안에 알맞은 수를 구하시오.",
                "body": ["213 + 382 = 5□5"],
                "answer": "9",
                "accepted": ["9", "595"],
                "answer_display": "9",
            },
            {
                "id": "g3_05",
                "source": "6페이지 05",
                "section": "1.1.1 받아올림이 없는 세 자리 수의 덧셈",
                "type": "choice",
                "prompt": "계산하시오.",
                "latex": r"220 + 516",
                "answer": "736",
                "accepted": ["736"],
                "answer_display": "736",
            },
            {
                "id": "g3_06",
                "source": "7페이지 01",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "수 모형을 보고 계산해 보시오.",
                "latex": r"134 + 323 = \Box",
                "answer": "457",
                "accepted": ["457"],
                "answer_display": "457",
            },
            {
                "id": "g3_07",
                "source": "7페이지 02",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "135와 624를 전개식으로 더할 때 빈칸에 알맞은 수를 차례대로 쓰시오.",
                "body": ["135=100+30+5", "624=600+20+4", "□ + □ + □", "135+624=□"],
                "answer": "700,50,9,759",
                "accepted": ["700,50,9,759", "700 50 9 759", "700/50/9/759"],
                "answer_display": "700, 50, 9, 759",
            },
            {
                "id": "g3_08",
                "source": "7페이지 03",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "324+251을 계산할 때 □ 안에 알맞은 수를 차례대로 쓰시오.",
                "body": ["300+200=□", "24+51=□", "324+251=□"],
                "answer": "500,75,575",
                "accepted": ["500,75,575", "500 75 575", "500/75/575"],
                "answer_display": "500, 75, 575",
            },
            {
                "id": "g3_09",
                "source": "7페이지 04",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "342+117의 계산으로 옳지 않은 것은 어느 것입니까?",
                "choices": [
                    {"value": "1", "label": "①", "text": "342는 백 모형 3개, 십 모형 4개, 일 모형 2개입니다."},
                    {"value": "2", "label": "②", "text": "117은 백 모형 1개, 십 모형 1개, 일 모형 7개입니다."},
                    {"value": "3", "label": "③", "text": "백 모형끼리 더하면 백 모형은 5개입니다."},
                    {"value": "4", "label": "④", "text": "일 모형끼리 더하면 일 모형은 9개입니다."},
                    {"value": "5", "label": "⑤", "text": "342+117은 459입니다."},
                ],
                "answer": "3",
                "answer_display": "③",
            },
            {
                "id": "g3_10",
                "source": "8페이지 08",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "246+532의 계산 과정을 보고 ㉠과 ㉡을 바르게 구한 것을 고르시오.",
                "choices": [
                    {"value": "1", "label": "①", "text": "㉠ 32, ㉡ 632"},
                    {"value": "2", "label": "②", "text": "㉠ 32, ㉡ 732"},
                    {"value": "3", "label": "③", "text": "㉠ 78, ㉡ 678"},
                    {"value": "4", "label": "④", "text": "㉠ 78, ㉡ 778"},
                    {"value": "5", "label": "⑤", "text": "㉠ 96, ㉡ 796"},
                ],
                "answer": "4",
                "answer_display": "④ ㉠ 78, ㉡ 778",
            },
            {
                "id": "g3_11",
                "source": "8페이지 09",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "어느 놀이공원에 어른은 275명 입장했고, 어린이는 어른보다 413명 더 많이 입장했습니다. 입장한 어린이는 몇 명인지 구하시오.",
                "answer": "688",
                "accepted": ["688", "688명"],
                "answer_display": "688명",
            },
            {
                "id": "g3_12",
                "source": "8페이지 10",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "덧셈식 ㉠, ㉡의 계산 결과를 차례대로 나열한 것을 고르시오.",
                "body": ["㉠ 613+120", "㉡ 322+456"],
                "choices": [
                    {"value": "1", "label": "①", "text": "778, 733"},
                    {"value": "2", "label": "②", "text": "778, 719"},
                    {"value": "3", "label": "③", "text": "733, 778"},
                    {"value": "4", "label": "④", "text": "733, 719"},
                    {"value": "5", "label": "⑤", "text": "719, 778"},
                ],
                "answer": "3",
                "answer_display": "③ 733, 778",
            },
            {
                "id": "g3_13",
                "source": "8페이지 11",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "혜주는 340원, 지원이는 520원을 가지고 있습니다. 두 사람이 가지고 있는 돈은 모두 몇 원인지 구하시오.",
                "answer": "860",
                "accepted": ["860", "860원"],
                "answer_display": "860원",
            },
            {
                "id": "g3_14",
                "source": "9페이지 01",
                "section": "1차 학습 1.1.1",
                "type": "choice",
                "prompt": "수 모형을 보고 계산해 보시오.",
                "latex": r"145 + 332 = \Box",
                "answer": "477",
                "accepted": ["477"],
                "answer_display": "477",
            },
            {
                "id": "g3_15",
                "source": "10페이지 07",
                "section": "1차 학습 1.1.1",
                "type": "choice",
                "prompt": "346+432의 계산 과정을 보고 ㉠과 ㉡을 바르게 구한 것을 고르시오.",
                "choices": [
                    {"value": "1", "label": "①", "text": "㉠ 6, ㉡ 667"},
                    {"value": "2", "label": "②", "text": "㉠ 6, ㉡ 678"},
                    {"value": "3", "label": "③", "text": "㉠ 8, ㉡ 776"},
                    {"value": "4", "label": "④", "text": "㉠ 8, ㉡ 777"},
                    {"value": "5", "label": "⑤", "text": "㉠ 8, ㉡ 778"},
                ],
                "answer": "5",
                "answer_display": "⑤ ㉠ 8, ㉡ 778",
            },
            {
                "id": "g3_16",
                "source": "11페이지 09",
                "section": "1차 학습 1.1.1",
                "type": "choice",
                "prompt": "어느 나라에 남자가 256명, 여자가 241명 살고 있습니다. 이 나라에 사는 사람은 모두 몇 명인지 구하시오.",
                "answer": "497",
                "accepted": ["497", "497명"],
                "answer_display": "497명",
            },
            {
                "id": "g3_17",
                "source": "34페이지 05",
                "section": "1.2.1 받아내림이 없는 세 자리 수의 뺄셈",
                "type": "choice",
                "prompt": "계산하시오.",
                "latex": r"729 - 516",
                "answer": "213",
                "accepted": ["213"],
                "answer_display": "213",
            },
            {
                "id": "g3_18",
                "source": "뺄셈 1차 학습 01",
                "section": "세 자리 수의 뺄셈",
                "type": "choice",
                "prompt": "뺄셈을 하시오.",
                "latex": r"729 - 591 = \Box",
                "answer": "138",
                "accepted": ["138"],
                "answer_display": "138",
            },
            {
                "id": "g3_19",
                "source": "뺄셈 1차 학습 05",
                "section": "세 자리 수의 뺄셈",
                "type": "choice",
                "prompt": "계산 결과의 크기를 비교하여 더 큰 것의 계산 결과를 구하시오.",
                "body": ["426-152", "516-261"],
                "answer": "274",
                "accepted": ["274"],
                "answer_display": "274",
            },
            {
                "id": "g3_20",
                "source": "뺄셈 1차 학습 10",
                "section": "세 자리 수의 뺄셈",
                "type": "choice",
                "prompt": "어린이 도서관에 책이 908권 있었습니다. 학생들이 책을 빌려가 도서관에 672권이 남았을 때 빌려간 책은 몇 권인지 구하시오.",
                "answer": "236",
                "accepted": ["236", "236권"],
                "answer_display": "236권",
            },
        ],
    },
    "grade6-1": {
        "id": "grade6-1",
        "title": "수와 연산 6-1",
        "grade": "초등 6-1",
        "source_file": "수와 연산 6-1(완성본).hwp",
        "description": "분수의 나눗셈과 소수의 나눗셈 객관식 시험",
        "workbook": {
            "page_count": 35,
            "static_directory": "math_workbooks/grade6-1",
        },
        "questions": [
            {
                "id": "g6_01",
                "source": "4페이지 확인1",
                "section": "1.1.1 (자연수) ÷ (자연수)",
                "type": "choice",
                "prompt": "다음 □ 안에 알맞은 수를 분수로 나타내시오.",
                "latex": r"1 \div 7 = \Box",
                "answer": "1/7",
                "accepted": ["1/7", "7분의1", "7분의 1"],
                "answer_display": r"\(\frac{1}{7}\)",
            },
            {
                "id": "g6_02",
                "source": "7페이지 02",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "다음 나눗셈의 몫을 분수로 나타내시오.",
                "latex": r"1 \div 15",
                "answer": "1/15",
                "accepted": ["1/15", "15분의1", "15분의 1"],
                "answer_display": r"\(\frac{1}{15}\)",
            },
            {
                "id": "g6_03",
                "source": "7페이지 04",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "나눗셈의 몫을 분수로 나타내시오.",
                "latex": r"5 \div 11",
                "answer": "5/11",
                "accepted": ["5/11", "11분의5", "11분의 5"],
                "answer_display": r"\(\frac{5}{11}\)",
            },
            {
                "id": "g6_04",
                "source": "8페이지 09",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "어떤 수를 4로 나누어야 할 것을 잘못하여 곱했더니 36이 되었습니다. 바르게 계산한 몫을 가분수로 나타내시오.",
                "answer": "9/4",
                "accepted": ["9/4", "4분의9", "4분의 9"],
                "answer_display": r"\(\frac{9}{4}\)",
            },
            {
                "id": "g6_05",
                "source": "8페이지 12",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "계산 결과의 크기를 비교하여 ○ 안에 >, =, < 중 알맞은 것을 고르시오.",
                "latex": r"4 \div 12 \ \circ \ 6 \div 30",
                "choices": [
                    {"value": "1", "label": "①", "text": ">"},
                    {"value": "2", "label": "②", "text": "="},
                    {"value": "3", "label": "③", "text": "<"},
                ],
                "answer": "1",
                "answer_display": "① >",
            },
            {
                "id": "g6_06",
                "source": "8페이지 13",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "다음 중 계산 결과가 가장 큰 것은 어느 것입니까?",
                "choices": [
                    {"value": "1", "label": "①", "text": "5÷4"},
                    {"value": "2", "label": "②", "text": "7÷6"},
                    {"value": "3", "label": "③", "text": "5÷6"},
                    {"value": "4", "label": "④", "text": "4÷5"},
                    {"value": "5", "label": "⑤", "text": "4÷7"},
                ],
                "answer": "1",
                "answer_display": "① 5÷4",
            },
            {
                "id": "g6_07",
                "source": "9페이지 14",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "1L 주스를 크기가 같은 5개의 컵에 똑같이 나누어 담는다면 한 컵에 몇 L씩 담을 수 있는지 분수로 나타내시오.",
                "answer": "1/5",
                "accepted": ["1/5", "5분의1", "5분의 1"],
                "answer_display": r"\(\frac{1}{5}\)L",
            },
            {
                "id": "g6_08",
                "source": "9페이지 15",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "소금 3kg을 봉지 8개에 똑같이 나누어 담았습니다. 한 개의 봉지에는 소금이 몇 kg 담겨 있는지 분수로 나타내시오.",
                "answer": "3/8",
                "accepted": ["3/8", "8분의3", "8분의 3"],
                "answer_display": r"\(\frac{3}{8}\)kg",
            },
            {
                "id": "g6_09",
                "source": "9페이지 17",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "샌드위치 5인분을 만드는 데 양파 1개가 필요합니다. 샌드위치 4인분을 만들려면 양파 몇 개가 필요한지 기약분수로 나타내시오.",
                "answer": "4/5",
                "accepted": ["4/5", "5분의4", "5분의 4"],
                "answer_display": r"\(\frac{4}{5}\)개",
            },
            {
                "id": "g6_10",
                "source": "9페이지 18",
                "section": "필수예제 1.1.1",
                "type": "choice",
                "prompt": "넓이가 14cm²이고 가로가 3cm인 직사각형이 있습니다. 이 직사각형의 세로는 몇 cm인지 대분수인 기약분수로 나타내시오.",
                "answer": "4 2/3",
                "accepted": ["4 2/3", "4와2/3", "4와 3분의 2", "4와3분의2", "14/3", "3분의14"],
                "answer_display": r"\(4\frac{2}{3}\)cm",
            },
            {
                "id": "g6_11",
                "source": "39페이지 01",
                "section": "3.1.1 자연수의 나눗셈을 이용한 (소수)÷(자연수)",
                "type": "choice",
                "prompt": "끈 69.3cm를 3명이 똑같이 나누어 가지려고 합니다. 69.3cm는 693mm입니다. 한 명이 가질 수 있는 끈의 길이를 mm, cm 순서로 쓰시오.",
                "answer": "231,23.1",
                "accepted": ["231,23.1", "231 23.1", "231mm 23.1cm"],
                "answer_display": "231mm, 23.1cm",
            },
            {
                "id": "g6_12",
                "source": "40페이지 07",
                "section": "3.1.1 자연수의 나눗셈을 이용한 (소수)÷(자연수)",
                "type": "choice",
                "prompt": "1g짜리 분동 6개와 0.1g짜리 분동 4개를 2개의 접시에 똑같이 나누어 담으려고 합니다. 접시 한 개에 담은 분동의 무게는 몇 g입니까?",
                "answer": "3.2",
                "accepted": ["3.2", "3.2g"],
                "answer_display": "3.2g",
            },
            {
                "id": "g6_13",
                "source": "40페이지 08",
                "section": "3.1.1 자연수의 나눗셈을 이용한 (소수)÷(자연수)",
                "type": "choice",
                "prompt": "대파 4묶음의 무게가 4.4kg일 때 대파 한 묶음의 무게는 몇 kg인지 구하시오.",
                "answer": "1.1",
                "accepted": ["1.1", "1.1kg"],
                "answer_display": "1.1kg",
            },
            {
                "id": "g6_14",
                "source": "41페이지 01",
                "section": "3.1.1 자연수의 나눗셈을 이용한 (소수)÷(자연수)",
                "type": "choice",
                "prompt": "줄 24.8cm를 2명에게 똑같이 나누어 주려고 합니다. ㉠, ㉡, ㉢, ㉣에 알맞은 수를 차례대로 쓰시오.",
                "body": ["1cm=10mm이므로 24.8cm=㉠mm입니다.", "248÷2=㉡", "한 명이 받을 수 있는 줄은 ㉢mm이므로 ㉣cm입니다."],
                "answer": "248,124,124,12.4",
                "accepted": ["248,124,124,12.4", "248 124 124 12.4"],
                "answer_display": "248, 124, 124, 12.4",
            },
            {
                "id": "g6_15",
                "source": "41페이지 02",
                "section": "3.1.1 자연수의 나눗셈을 이용한 (소수)÷(자연수)",
                "type": "choice",
                "prompt": "936÷3=312를 이용하여 ㉠과 ㉡에 알맞은 수를 차례대로 쓰시오.",
                "body": ["93.6÷3=㉠", "9.36÷3=㉡"],
                "answer": "31.2,3.12",
                "accepted": ["31.2,3.12", "31.2 3.12"],
                "answer_display": "31.2, 3.12",
            },
            {
                "id": "g6_16",
                "source": "42페이지 05",
                "section": "3.1.1 자연수의 나눗셈을 이용한 (소수)÷(자연수)",
                "type": "choice",
                "prompt": "계산하시오.",
                "latex": r"8.84 \div 4",
                "answer": "2.21",
                "accepted": ["2.21"],
                "answer_display": "2.21",
            },
            {
                "id": "g6_17",
                "source": "42페이지 08",
                "section": "3.1.1 자연수의 나눗셈을 이용한 (소수)÷(자연수)",
                "type": "choice",
                "prompt": "텃밭 15.55m²를 학생 5명이 똑같이 나누어 가꾸고 있습니다. 학생 한 명이 가꾸는 텃밭의 넓이는 몇 m²인지 구하시오.",
                "answer": "3.11",
                "accepted": ["3.11", "3.11m2", "3.11m²"],
                "answer_display": "3.11m²",
            },
            {
                "id": "g6_18",
                "source": "46페이지 07",
                "section": "3.1.2 각 자리에서 나누어떨어지지 않는 (소수)÷(자연수)",
                "type": "choice",
                "prompt": "두 식의 몫의 차를 구하시오.",
                "body": ["29.25÷13", "37.52÷7"],
                "answer": "3.11",
                "accepted": ["3.11"],
                "answer_display": "3.11",
            },
            {
                "id": "g6_19",
                "source": "47페이지 15",
                "section": "3.1.2 각 자리에서 나누어떨어지지 않는 (소수)÷(자연수)",
                "type": "choice",
                "prompt": "무게가 같은 동화책 7권과 잡지 7권의 무게가 20.23kg입니다. 잡지 한 권의 무게가 1.53kg이라면 동화책 한 권의 무게는 몇 kg입니까?",
                "answer": "1.36",
                "accepted": ["1.36", "1.36kg"],
                "answer_display": "1.36kg",
            },
            {
                "id": "g6_20",
                "source": "50페이지 15",
                "section": "3.1.2 각 자리에서 나누어떨어지지 않는 (소수)÷(자연수)",
                "type": "choice",
                "prompt": "K사 승용차는 3시간 동안 248.73km를 가고, H사 승용차는 5시간 동안 472.55km를 갑니다. 한 시간 동안 달릴 때 H사 승용차는 K사 승용차보다 몇 km 더 멀리 가는지 구하시오.",
                "answer": "11.6",
                "accepted": ["11.6", "11.6km"],
                "answer_display": "11.6km",
            },
        ],
    },
}


CHOICE_LABELS = ["①", "②", "③", "④", "⑤"]


MULTIPLE_CHOICE_OVERRIDES = {
    "g3_02": {
        "answer": "2",
        "options": ["486", "496", "506", "594", "596"],
    },
    "g3_04": {
        "answer": "2",
        "options": ["8", "9", "7", "6", "5"],
    },
    "g3_05": {
        "answer": "2",
        "options": ["726", "736", "746", "636", "756"],
    },
    "g3_06": {
        "answer": "2",
        "options": ["447", "457", "467", "357", "754"],
    },
    "g3_07": {
        "answer": "2",
        "options": [
            "600, 50, 9, 659",
            "700, 50, 9, 759",
            "700, 60, 9, 769",
            "700, 50, 8, 758",
            "700, 30, 9, 739",
        ],
    },
    "g3_08": {
        "answer": "2",
        "options": [
            "400, 75, 475",
            "500, 75, 575",
            "500, 65, 565",
            "500, 85, 585",
            "600, 75, 675",
        ],
    },
    "g3_11": {
        "answer": "2",
        "options": ["578명", "688명", "698명", "413명", "275명"],
    },
    "g3_13": {
        "answer": "2",
        "options": ["760원", "860원", "840원", "880원", "520원"],
    },
    "g3_14": {
        "answer": "2",
        "options": ["467", "477", "487", "577", "433"],
    },
    "g3_16": {
        "answer": "2",
        "options": ["487명", "497명", "507명", "597명", "241명"],
    },
    "g3_17": {
        "answer": "2",
        "options": ["203", "213", "223", "313", "215"],
    },
    "g3_18": {
        "answer": "2",
        "options": ["128", "138", "148", "238", "132"],
    },
    "g3_19": {
        "answer": "1",
        "options": ["274", "255", "264", "284", "526"],
    },
    "g3_20": {
        "answer": "2",
        "options": ["226권", "236권", "246권", "326권", "672권"],
    },
    "g6_01": {
        "answer": "2",
        "options": [
            r"\(\frac{1}{6}\)",
            r"\(\frac{1}{7}\)",
            r"\(\frac{7}{1}\)",
            r"\(\frac{6}{1}\)",
            r"\(\frac{7}{10}\)",
        ],
    },
    "g6_02": {
        "answer": "2",
        "options": [
            r"\(\frac{1}{14}\)",
            r"\(\frac{1}{15}\)",
            r"\(\frac{15}{1}\)",
            r"\(\frac{1}{5}\)",
            r"\(\frac{15}{10}\)",
        ],
    },
    "g6_03": {
        "answer": "2",
        "options": [
            r"\(\frac{11}{5}\)",
            r"\(\frac{5}{11}\)",
            r"\(\frac{1}{11}\)",
            r"\(\frac{5}{10}\)",
            r"\(\frac{6}{11}\)",
        ],
    },
    "g6_04": {
        "answer": "2",
        "options": [
            r"\(\frac{4}{9}\)",
            r"\(\frac{9}{4}\)",
            "9",
            "4",
            r"\(\frac{36}{4}\)",
        ],
    },
    "g6_07": {
        "answer": "2",
        "options": [
            r"\(\frac{1}{4}\)L",
            r"\(\frac{1}{5}\)L",
            r"\(\frac{5}{1}\)L",
            r"\(\frac{2}{5}\)L",
            "5L",
        ],
    },
    "g6_08": {
        "answer": "2",
        "options": [
            r"\(\frac{1}{8}\)kg",
            r"\(\frac{3}{8}\)kg",
            r"\(\frac{8}{3}\)kg",
            r"\(\frac{3}{5}\)kg",
            "8kg",
        ],
    },
    "g6_09": {
        "answer": "2",
        "options": [
            r"\(\frac{1}{5}\)개",
            r"\(\frac{4}{5}\)개",
            r"\(\frac{5}{4}\)개",
            "4개",
            "5개",
        ],
    },
    "g6_10": {
        "answer": "2",
        "options": [
            r"\(3\frac{2}{3}\)cm",
            r"\(4\frac{2}{3}\)cm",
            r"\(4\frac{1}{3}\)cm",
            r"\(\frac{14}{4}\)cm",
            "17cm",
        ],
    },
    "g6_11": {
        "answer": "2",
        "options": [
            "213mm, 21.3cm",
            "231mm, 23.1cm",
            "231mm, 2.31cm",
            "693mm, 69.3cm",
            "23.1mm, 231cm",
        ],
    },
    "g6_12": {
        "answer": "2",
        "options": ["3.1g", "3.2g", "6.4g", "2.3g", "3.4g"],
    },
    "g6_13": {
        "answer": "2",
        "options": ["0.11kg", "1.1kg", "1.4kg", "4.1kg", "17.6kg"],
    },
    "g6_14": {
        "answer": "2",
        "options": [
            "248, 124, 124, 1.24",
            "248, 124, 124, 12.4",
            "24.8, 12.4, 12.4, 124",
            "248, 248, 124, 12.4",
            "248, 124, 12.4, 124",
        ],
    },
    "g6_15": {
        "answer": "2",
        "options": ["312, 31.2", "31.2, 3.12", "3.12, 31.2", "93.6, 9.36", "312, 3.12"],
    },
    "g6_16": {
        "answer": "2",
        "options": ["2.12", "2.21", "22.1", "0.221", "3.21"],
    },
    "g6_17": {
        "answer": "2",
        "options": ["3.01m²", "3.11m²", "31.1m²", "2.11m²", "5.11m²"],
    },
    "g6_18": {
        "answer": "2",
        "options": ["2.25", "3.11", "5.36", "7.61", "1.31"],
    },
    "g6_19": {
        "answer": "2",
        "options": ["1.26kg", "1.36kg", "1.46kg", "2.89kg", "10.71kg"],
    },
    "g6_20": {
        "answer": "2",
        "options": ["10.6km", "11.6km", "12.6km", "82.91km", "94.51km"],
    },
}


def _build_choices(options):
    return [
        {"value": str(index + 1), "label": CHOICE_LABELS[index], "text": option}
        for index, option in enumerate(options)
    ]


def _apply_multiple_choice_format():
    for exam in MATH_EXAMS.values():
        for question in exam["questions"]:
            override = MULTIPLE_CHOICE_OVERRIDES.get(question["id"])
            if override:
                choices = _build_choices(override["options"])
                answer_index = int(override["answer"]) - 1
                question["type"] = "choice"
                question["choices"] = choices
                question["answer"] = override["answer"]
                question["answer_display"] = f"{choices[answer_index]['label']} {choices[answer_index]['text']}"
                question.pop("accepted", None)
                continue

            choice_values = [choice["value"] for choice in question.get("choices", [])]
            if question.get("type") != "choice" or not choice_values or question.get("answer") not in choice_values:
                raise ValueError(f"Math question must be multiple-choice: {question['id']}")


_apply_multiple_choice_format()


def get_math_exams():
    return list(MATH_EXAMS.values())


def get_math_exam(exam_id):
    return MATH_EXAMS.get(exam_id)
