EXTRA_VILLAGE_BLUEPRINTS = {
    6: {
        "theme_ko": "사람들",
        "theme_en": "People",
        "summary": "사람을 소개하고 직업과 관계를 묻고 답하는 표현을 연습합니다.",
        "lessons": [
            {
                "title": "She is my classmate.",
                "prompt": "Who is she?",
                "response": "She is my classmate.",
                "practice_keywords": ["he", "they", "that man"],
            },
            {
                "title": "Look at the baby!",
                "prompt": "Look at the baby!",
                "response": "Aww, so cute!",
                "practice_keywords": ["boy", "girl", "gentleman"],
            },
            {
                "title": "He is my hero.",
                "prompt": "Who is your hero?",
                "response": "My dad!",
                "practice_keywords": ["idol", "star", "role model"],
            },
            {
                "title": "Who works at the store?",
                "prompt": "Who works at the store?",
                "response": "A clerk works there.",
                "practice_keywords": ["hospital", "library", "bakery"],
            },
            {
                "title": "Is he a pilot?",
                "prompt": "Is he a pilot?",
                "response": "Yes, he flies planes.",
                "practice_keywords": ["scientist", "doctor", "artist"],
            },
            {
                "title": "Are you a customer?",
                "prompt": "Are you a customer?",
                "response": "Yes, I want to buy juice.",
                "practice_keywords": ["client", "shopper", "guest"],
            },
            {
                "title": "What's your job?",
                "prompt": "What's your job?",
                "response": "I'm a model.",
                "practice_keywords": ["firefighter", "police officer", "athlete"],
            },
            {
                "title": "We are a team.",
                "prompt": "Are we a team?",
                "response": "Yes! Let's win!",
                "practice_keywords": ["same group", "same club", "same side"],
            },
            {
                "title": "I want to be a teacher.",
                "prompt": "What do you want to be?",
                "response": "I want to be a teacher.",
                "practice_keywords": ["lawyer", "chef", "farmer"],
            },
            {
                "title": "Yes, he is my friend.",
                "prompt": "Is he your friend?",
                "response": "Yes, he is my friend.",
                "practice_keywords": ["teacher", "cousin", "neighbor"],
            },
            {
                "title": "Is she famous?",
                "prompt": "Is she famous?",
                "response": "Yes, she is.",
                "practice_keywords": ["popular", "well-known", "star"],
            },
            {
                "title": "Yes, there are many people.",
                "prompt": "Are there many people?",
                "response": "Yes, there are many people.",
                "practice_keywords": ["visitors", "audience", "participants"],
            },
        ],
    },
    7: {
        "theme_ko": "백화점",
        "theme_en": "Department Store",
        "summary": "옷을 고르고 계산하며 백화점에서 자주 쓰는 쇼핑 표현을 익힙니다.",
        "lessons": [
            {
                "title": "Let's go shopping!",
                "prompt": "Let's go shopping!",
                "response": "Yes! I need a new dress.",
                "practice_keywords": ["pants", "sneakers", "jacket"],
            },
            {
                "title": "Try this coat.",
                "prompt": "Try this coat.",
                "response": "It's too big.",
                "practice_keywords": ["sweater", "jeans", "boots"],
            },
            {
                "title": "What size is this?",
                "prompt": "What size is this?",
                "response": "It's small.",
                "practice_keywords": ["color", "brand", "material"],
            },
            {
                "title": "I like that jacket.",
                "prompt": "I like that jacket.",
                "response": "It looks cool!",
                "practice_keywords": ["suit", "cardigan", "tie"],
            },
            {
                "title": "How much is it?",
                "prompt": "How much is it?",
                "response": "It's on sale! It's 20 dollars.",
                "practice_keywords": ["price", "discount", "promotion"],
            },
            {
                "title": "Where is the kids' section?",
                "prompt": "Where is the kids' section?",
                "response": "It's on the third floor.",
                "practice_keywords": ["men", "women", "baby"],
            },
            {
                "title": "Wait in line.",
                "prompt": "Let's buy it!",
                "response": "Okay. Let's wait in line.",
                "practice_keywords": ["take it", "grab it", "wait our turn"],
            },
            {
                "title": "Put it in the bag.",
                "prompt": "Here's your shirt.",
                "response": "Put it in the bag.",
                "practice_keywords": ["skirt", "hat", "blouse"],
            },
            {
                "title": "Look at the clothes!",
                "prompt": "Look at the clothes!",
                "response": "So pretty!",
                "practice_keywords": ["suits", "boots", "shirts"],
            },
            {
                "title": "I got a voucher!",
                "prompt": "What's that?",
                "response": "I got a voucher!",
                "practice_keywords": ["coupon", "gift card", "promotion code"],
            },
            {
                "title": "I saw it on TV.",
                "prompt": "Where did you see it?",
                "response": "I saw it on TV.",
                "practice_keywords": ["magazine", "social media", "drama"],
            },
            {
                "title": "Let's go shopping this weekend.",
                "prompt": "Let's go shopping this weekend.",
                "response": "Great idea!",
                "practice_keywords": ["holiday", "day off", "vacation"],
            },
        ],
    },
    8: {
        "theme_ko": "과일 가게",
        "theme_en": "Fruit Shop",
        "summary": "과일 이름을 말하고 사고 싶은 물건과 맛, 가격을 묻는 표현을 연습합니다.",
        "lessons": [
            {
                "title": "What fruit is this?",
                "prompt": "What fruit is this?",
                "response": "It's a banana.",
                "practice_keywords": ["apple", "pear", "watermelon"],
            },
            {
                "title": "I like watermelon.",
                "prompt": "What fruit do you like?",
                "response": "I like watermelon.",
                "practice_keywords": ["orange", "tangerine", "lemon"],
            },
            {
                "title": "Let's buy tomatoes.",
                "prompt": "Let's buy tomatoes.",
                "response": "Okay. They look red and fresh.",
                "practice_keywords": ["peaches", "strawberries", "grapes"],
            },
            {
                "title": "Can I try one cherry?",
                "prompt": "Can I try one cherry?",
                "response": "Sure. Go ahead.",
                "practice_keywords": ["grape", "blueberry", "raspberry"],
            },
            {
                "title": "This orange is big!",
                "prompt": "This orange is big!",
                "response": "Let's buy it!",
                "practice_keywords": ["papaya", "avocado", "fig"],
            },
            {
                "title": "Can I pay here?",
                "prompt": "Can I pay here?",
                "response": "Yes, please pay here.",
                "practice_keywords": ["check out", "right here", "counter"],
            },
            {
                "title": "The shop is open!",
                "prompt": "The shop is open!",
                "response": "Let's go in!",
                "practice_keywords": ["store", "market", "grocery"],
            },
            {
                "title": "Do you have a pineapple?",
                "prompt": "Do you have a pineapple?",
                "response": "Yes, they're fresh today.",
                "practice_keywords": ["plum", "melon", "mango"],
            },
            {
                "title": "Are these grapes sweet?",
                "prompt": "Are these grapes sweet?",
                "response": "Yes, they are sweet.",
                "practice_keywords": ["limes", "kiwis", "pomegranate"],
            },
            {
                "title": "It's one dollar.",
                "prompt": "How much is this banana?",
                "response": "It's one dollar.",
                "practice_keywords": ["mulberry", "persimmon", "cranberry"],
            },
            {
                "title": "Is this apricot ripe?",
                "prompt": "Is this apricot ripe?",
                "response": "Yes, it's ready now.",
                "practice_keywords": ["blackberry", "dragon fruit", "avocado"],
            },
            {
                "title": "Can you cut this pineapple?",
                "prompt": "Can you cut this pineapple?",
                "response": "Sure. No problem.",
                "practice_keywords": ["slice", "peel", "chop"],
            },
        ],
    },
    9: {
        "theme_ko": "레스토랑",
        "theme_en": "Restaurant",
        "summary": "식당에서 음식과 음료를 주문하고 맛과 결제를 말하는 표현을 익힙니다.",
        "lessons": [
            {
                "title": "What's for lunch?",
                "prompt": "What's for lunch?",
                "response": "Chicken and rice.",
                "practice_keywords": ["dinner", "breakfast", "snack time"],
            },
            {
                "title": "Asking for water.",
                "prompt": "Can I have some water?",
                "response": "Here is a bottle.",
                "practice_keywords": ["juice", "coffee", "milk"],
            },
            {
                "title": "Breakfast time.",
                "prompt": "Is it breakfast time?",
                "response": "Yes! I'm hungry.",
                "practice_keywords": ["lunch", "dinner", "snack"],
            },
            {
                "title": "Do you like spaghetti?",
                "prompt": "Do you like spaghetti?",
                "response": "Yes! It's tasty.",
                "practice_keywords": ["fried rice", "burger", "chicken wings"],
            },
            {
                "title": "Ordering a sandwich.",
                "prompt": "Can I have a sandwich?",
                "response": "Sure. With beef or chicken?",
                "practice_keywords": ["salad", "ramen", "stir-fried vegetables"],
            },
            {
                "title": "The soup is hot.",
                "prompt": "The soup is hot.",
                "response": "Blow on it!",
                "practice_keywords": ["noodle", "pizza", "beef steak"],
            },
            {
                "title": "Do you eat fish?",
                "prompt": "Do you eat fish?",
                "response": "Yes, I love it.",
                "practice_keywords": ["crab", "cucumber", "dairy"],
            },
            {
                "title": "Are you allergic to any food?",
                "prompt": "Are you allergic to any food?",
                "response": "Yes, I'm allergic to nuts.",
                "practice_keywords": ["milk", "shrimp", "food allergies"],
            },
            {
                "title": "Let's eat steak.",
                "prompt": "Let's eat steak.",
                "response": "I love steak!",
                "practice_keywords": ["pasta", "sushi", "pizza"],
            },
            {
                "title": "How is your soup?",
                "prompt": "How is your soup?",
                "response": "It's the best!",
                "practice_keywords": ["your meal", "the food", "everything"],
            },
            {
                "title": "Can I have the check?",
                "prompt": "Can I have the check?",
                "response": "Yes, here you go.",
                "practice_keywords": ["bill", "pay now", "receipt"],
            },
            {
                "title": "Paying the bill.",
                "prompt": "Here is the bill.",
                "response": "Okay. I will pay.",
                "practice_keywords": ["tab", "check", "receipt"],
            },
        ],
    },
    10: {
        "theme_ko": "카페",
        "theme_en": "Cafe",
        "summary": "카페에서 음료와 디저트를 주문하고 맛과 분위기를 말하는 표현을 연습합니다.",
        "lessons": [
            {
                "title": "Do you want coffee?",
                "prompt": "Do you want coffee?",
                "response": "Yes, with milk, please.",
                "practice_keywords": ["juice", "milkshake", "tea"],
            },
            {
                "title": "I want juice.",
                "prompt": "What do you want?",
                "response": "I want juice.",
                "practice_keywords": ["coffee", "ice cream", "tea"],
            },
            {
                "title": "Can I have a coffee?",
                "prompt": "Can I have a coffee?",
                "response": "Sure. What size?",
                "practice_keywords": ["latte", "americano", "milk"],
            },
            {
                "title": "Do you have any cake?",
                "prompt": "Do you have any cake?",
                "response": "Yes, we do.",
                "practice_keywords": ["cookies", "bread", "sandwiches"],
            },
            {
                "title": "Do you want a cookie?",
                "prompt": "Do you want a cookie?",
                "response": "Yes, and a spoon too!",
                "practice_keywords": ["cake", "yogurt", "bread"],
            },
            {
                "title": "I love biscuits.",
                "prompt": "I love biscuits.",
                "response": "Me too, with jam!",
                "practice_keywords": ["pie", "muffin", "maple syrup"],
            },
            {
                "title": "What did you order?",
                "prompt": "What did you order?",
                "response": "A donut.",
                "practice_keywords": ["tart", "cupcake", "scone"],
            },
            {
                "title": "Do you have any cold drinks?",
                "prompt": "Do you have any cold drinks?",
                "response": "Yes, lemonade.",
                "practice_keywords": ["hot tea", "coffee", "milkshake"],
            },
            {
                "title": "What's today's special?",
                "prompt": "What's today's special?",
                "response": "Today's special is mango smoothie.",
                "practice_keywords": ["iced lemon tea", "strawberry latte", "peach juice"],
            },
            {
                "title": "Can I get a to-go cup?",
                "prompt": "Can I get a to-go cup?",
                "response": "Of course, here you go.",
                "practice_keywords": ["box", "container", "cup holder"],
            },
            {
                "title": "Can you make it less sweet?",
                "prompt": "Can you make it less sweet?",
                "response": "Sure. I will use less sugar.",
                "practice_keywords": ["salty", "bitter", "icy"],
            },
            {
                "title": "I like the music here.",
                "prompt": "I like the music here.",
                "response": "Yes. It sounds nice.",
                "practice_keywords": ["mood", "atmosphere", "vibe"],
            },
        ],
    },
    11: {
        "theme_ko": "동물원",
        "theme_en": "Zoo",
        "summary": "동물원에서 동물을 보고 특징과 위치를 말하는 기본 회화를 익힙니다.",
        "lessons": [
            {
                "title": "What's your favorite animal?",
                "prompt": "What's your favorite animal?",
                "response": "I love elephants. They are big and kind.",
                "practice_keywords": ["place", "pet", "bird"],
            },
            {
                "title": "Look at that lion!",
                "prompt": "Look at that lion!",
                "response": "Wow, it's walking near the rock.",
                "practice_keywords": ["giraffe", "zebra", "panda"],
            },
            {
                "title": "Do birds fly far?",
                "prompt": "Do birds fly far?",
                "response": "Yes! Some birds fly over the sea.",
                "practice_keywords": ["eat worms", "live in trees", "have feathers"],
            },
            {
                "title": "Is that a cow or a pig?",
                "prompt": "Is that a cow or a pig?",
                "response": "That's a pig. The cow is behind it.",
                "practice_keywords": ["turtle", "raccoon", "peacock"],
            },
            {
                "title": "Where are the bears?",
                "prompt": "Where are the bears?",
                "response": "They're in the cave.",
                "practice_keywords": ["koalas", "seals", "water"],
            },
            {
                "title": "Let's go see the fox.",
                "prompt": "Let's go see the fox.",
                "response": "Okay! I think it's near the forest.",
                "practice_keywords": ["elephant", "kangaroo", "meerkat"],
            },
            {
                "title": "Why is the bear sleeping?",
                "prompt": "Why is the bear sleeping?",
                "response": "It needs rest.",
                "practice_keywords": ["panda", "tiger", "rest"],
            },
            {
                "title": "Can the duck swim?",
                "prompt": "Can the duck swim?",
                "response": "Yes, it can.",
                "practice_keywords": ["penguin", "cheetah", "turtles"],
            },
            {
                "title": "Look at that bee!",
                "prompt": "Look at that bee!",
                "response": "Be careful. It can be dangerous.",
                "practice_keywords": ["spider", "chameleon", "peacock"],
            },
            {
                "title": "Did the bat fly away?",
                "prompt": "Did the bat fly away?",
                "response": "Yes, it flew over the tree.",
                "practice_keywords": ["eagle", "butterfly", "owl"],
            },
            {
                "title": "What time do we return?",
                "prompt": "What time do we return?",
                "response": "At three o'clock.",
                "practice_keywords": ["eat lunch", "go home", "break time"],
            },
            {
                "title": "I want to come back.",
                "prompt": "I want to come back.",
                "response": "Me too! Let's plan another zoo trip.",
                "practice_keywords": ["visit again", "stay longer", "awesome"],
            },
        ],
    },
    12: {
        "theme_ko": "여행",
        "theme_en": "Travel",
        "summary": "여행을 준비하고 이동하며 장소와 일정에 대해 묻는 표현을 연습합니다.",
        "lessons": [
            {
                "title": "When do we leave?",
                "prompt": "When do we leave?",
                "response": "Let's go after lunch.",
                "practice_keywords": ["leave soon", "3 o'clock", "5 o'clock"],
            },
            {
                "title": "Where will we go?",
                "prompt": "Where will we go?",
                "response": "To the farm. It's not far.",
                "practice_keywords": ["beach", "park", "mountain"],
            },
            {
                "title": "Who is coming with us?",
                "prompt": "Who is coming with us?",
                "response": "My family is coming with us.",
                "practice_keywords": ["family", "classmates", "pet"],
            },
            {
                "title": "Can we stop here?",
                "prompt": "Can we stop here?",
                "response": "Yes, this is a nice place.",
                "practice_keywords": ["good idea", "take a rest", "looks nice"],
            },
            {
                "title": "I remember this place.",
                "prompt": "I remember this place.",
                "response": "We ate here last year.",
                "practice_keywords": ["park", "bakery", "hotel"],
            },
            {
                "title": "Where's the restroom?",
                "prompt": "Where's the restroom?",
                "response": "It's at the front!",
                "practice_keywords": ["entrance", "stairs", "elevator"],
            },
            {
                "title": "What should we try today?",
                "prompt": "What should we try today?",
                "response": "Let's try fishing here.",
                "practice_keywords": ["hiking", "swimming", "camping"],
            },
            {
                "title": "Can we see the house again?",
                "prompt": "Can we see the house again?",
                "response": "Sure, I love that place!",
                "practice_keywords": ["museum", "park", "zoo"],
            },
            {
                "title": "When is the trip?",
                "prompt": "When is the trip?",
                "response": "It's on May 20th.",
                "practice_keywords": ["flight", "vacation", "tour"],
            },
            {
                "title": "I want to rest at home.",
                "prompt": "I want to rest at home.",
                "response": "Okay. We can go out again later.",
                "practice_keywords": ["in bed", "in my room", "on the couch"],
            },
            {
                "title": "I want to go to the top.",
                "prompt": "Do you want to go to the top of the hill?",
                "response": "Let's go!",
                "practice_keywords": ["hill", "tower", "mountain"],
            },
            {
                "title": "Did you finish packing?",
                "prompt": "Did you finish packing?",
                "response": "Not yet.",
                "practice_keywords": ["planning", "shopping", "preparing"],
            },
        ],
    },
    13: {
        "theme_ko": "자연",
        "theme_en": "Nature",
        "summary": "하늘과 바다, 계절과 날씨를 보며 자연을 묘사하는 표현을 익힙니다.",
        "lessons": [
            {
                "title": "Look at the sky!",
                "prompt": "Look at the sky!",
                "response": "I see a star.",
                "practice_keywords": ["rainbow", "moon", "clouds"],
            },
            {
                "title": "Do you like the sea?",
                "prompt": "Do you like the sea?",
                "response": "Yes, I swim there in summer.",
                "practice_keywords": ["park", "mountain", "forest"],
            },
            {
                "title": "It's raining now.",
                "prompt": "It's raining now.",
                "response": "Let's use an umbrella.",
                "practice_keywords": ["windy", "snowing", "sunny"],
            },
            {
                "title": "The mountain is high.",
                "prompt": "The mountain is high.",
                "response": "And the wind is cold.",
                "practice_keywords": ["valley", "hill", "forest"],
            },
            {
                "title": "I see snow!",
                "prompt": "I see snow!",
                "response": "It's winter now.",
                "practice_keywords": ["bird", "rainbow", "butterfly"],
            },
            {
                "title": "The grass is fresh.",
                "prompt": "The grass is fresh.",
                "response": "I love spring!",
                "practice_keywords": ["flowers", "trees", "leaves"],
            },
            {
                "title": "What season is it?",
                "prompt": "What season is it?",
                "response": "It's spring.",
                "practice_keywords": ["spring", "summer", "winter"],
            },
            {
                "title": "The river is quiet.",
                "prompt": "The river is quiet.",
                "response": "It feels peaceful.",
                "practice_keywords": ["lake", "pond", "ocean"],
            },
            {
                "title": "Let's go to the river.",
                "prompt": "Let's go to the river.",
                "response": "Okay! Bring some water and a snack.",
                "practice_keywords": ["lake", "beach", "park"],
            },
            {
                "title": "The sand is hot!",
                "prompt": "The sand is hot!",
                "response": "It's too sunny today.",
                "practice_keywords": ["wind", "water", "air"],
            },
            {
                "title": "Fire feels warm.",
                "prompt": "Fire feels warm.",
                "response": "Yes, but don't go too close.",
                "practice_keywords": ["sun", "sand", "water"],
            },
            {
                "title": "Do stars always shine?",
                "prompt": "Do stars always shine?",
                "response": "Yes, always.",
                "practice_keywords": ["planets", "moon", "sun"],
            },
        ],
    },
    14: {
        "theme_ko": "교통수단",
        "theme_en": "Transportation",
        "summary": "버스와 지하철, 택시와 비행기처럼 다양한 교통수단을 말하는 표현을 연습합니다.",
        "lessons": [
            {
                "title": "Let's take the bus!",
                "prompt": "Let's take the bus!",
                "response": "Okay. The bus is fast.",
                "practice_keywords": ["train", "subway", "taxi"],
            },
            {
                "title": "Do you have a bike?",
                "prompt": "Do you have a bike?",
                "response": "Yes! I ride it every morning.",
                "practice_keywords": ["car", "scooter", "skateboard"],
            },
            {
                "title": "Look! That car is big.",
                "prompt": "Look! That car is big.",
                "response": "It's a truck!",
                "practice_keywords": ["helicopter", "plane", "boat"],
            },
            {
                "title": "I want to take the train.",
                "prompt": "I want to take the train.",
                "response": "Me too. Let's go today.",
                "practice_keywords": ["flight", "ferry", "taxi"],
            },
            {
                "title": "Is that your boat?",
                "prompt": "Is that your boat?",
                "response": "No, mine is the small one.",
                "practice_keywords": ["motorcycle", "yacht", "car"],
            },
            {
                "title": "Let's go by subway.",
                "prompt": "Let's go by subway.",
                "response": "Okay. It's fast and easy.",
                "practice_keywords": ["bus", "train", "bike"],
            },
            {
                "title": "Can we take a taxi?",
                "prompt": "Can we take a taxi?",
                "response": "Sure. Let's call one.",
                "practice_keywords": ["bus", "plane", "subway"],
            },
            {
                "title": "Have you been on a ship?",
                "prompt": "Have you been on a ship?",
                "response": "Yes, once!",
                "practice_keywords": ["airplane", "train", "subway"],
            },
            {
                "title": "Do you like airplanes?",
                "prompt": "Do you like airplanes?",
                "response": "Yes, they're fun!",
                "practice_keywords": ["trains", "bikes", "ships"],
            },
            {
                "title": "Let's climb that hill.",
                "prompt": "Let's climb that hill.",
                "response": "That's too dangerous.",
                "practice_keywords": ["rock", "tree", "mountain"],
            },
            {
                "title": "We jumped in the lake!",
                "prompt": "We jumped in the lake!",
                "response": "After the boat ride, right?",
                "practice_keywords": ["lake", "sea", "pond"],
            },
            {
                "title": "How do you usually travel?",
                "prompt": "How do you usually travel?",
                "response": "By airplane.",
                "practice_keywords": ["airplane", "train", "bus"],
            },
        ],
    },
    15: {
        "theme_ko": "스포츠",
        "theme_en": "Sports",
        "summary": "운동을 하고 경기 장면을 말하며 스포츠 활동과 관련된 표현을 익힙니다.",
        "lessons": [
            {
                "title": "Do you like sports?",
                "prompt": "Do you like sports?",
                "response": "Yes! I play soccer.",
                "practice_keywords": ["badminton", "basketball", "tennis"],
            },
            {
                "title": "Let's play basketball.",
                "prompt": "Let's play basketball.",
                "response": "Catch the ball!",
                "practice_keywords": ["volleyball", "baseball", "tennis"],
            },
            {
                "title": "Can you play tennis?",
                "prompt": "Can you play tennis?",
                "response": "A little. Let's try!",
                "practice_keywords": ["badminton", "baseball", "basketball"],
            },
            {
                "title": "I like baseball.",
                "prompt": "I like baseball.",
                "response": "Me too! Let's play after school.",
                "practice_keywords": ["tennis", "soccer", "swimming"],
            },
            {
                "title": "Ready to race?",
                "prompt": "Ready to race?",
                "response": "Yes! One, two, three, go!",
                "practice_keywords": ["jump", "swim", "catch"],
            },
            {
                "title": "Let's run a marathon.",
                "prompt": "Let's run a marathon.",
                "response": "Wow! That takes energy!",
                "practice_keywords": ["exercise", "race", "stretch"],
            },
            {
                "title": "Hike with me!",
                "prompt": "Hike with me!",
                "response": "Sure! Let's go.",
                "practice_keywords": ["run", "swim", "play soccer"],
            },
            {
                "title": "That was a great goal!",
                "prompt": "That was a great goal!",
                "response": "Thanks! I love soccer.",
                "practice_keywords": ["great shot", "great serve", "great run"],
            },
            {
                "title": "Stand here.",
                "prompt": "Stand here.",
                "response": "Okay. I'll push the ball.",
                "practice_keywords": ["on the line", "by the net", "block the ball"],
            },
            {
                "title": "Sit and rest.",
                "prompt": "Sit and rest.",
                "response": "I ran too fast!",
                "practice_keywords": ["watch the game", "drink some water", "stretch"],
            },
            {
                "title": "Are you a fan of sports?",
                "prompt": "Are you a fan of sports?",
                "response": "Yes! Every weekend.",
                "practice_keywords": ["soccer", "baseball", "tennis"],
            },
            {
                "title": "Let's go home after the game!",
                "prompt": "Let's go home after the game!",
                "response": "That sounds good!",
                "practice_keywords": ["eat", "drink some water", "take a rest"],
            },
        ],
    },
    16: {
        "theme_ko": "복습",
        "theme_en": "Review",
        "summary": "what, where, when, who, how, why 같은 기본 질문과 핵심 회화 표현을 복습합니다.",
        "lessons": [
            {
                "title": "What is this?",
                "prompt": "What is this?",
                "response": "It's a pen.",
                "practice_keywords": ["locker", "alphabet", "corrector"],
            },
            {
                "title": "Where is he?",
                "prompt": "Where is he?",
                "response": "He's in the library.",
                "practice_keywords": ["teacher", "classroom", "playground"],
            },
            {
                "title": "When do we eat?",
                "prompt": "When do we eat?",
                "response": "At 12. Let's go!",
                "practice_keywords": ["play", "study", "trip"],
            },
            {
                "title": "Who is she?",
                "prompt": "Who is she?",
                "response": "She is my teacher.",
                "practice_keywords": ["they", "he", "that person"],
            },
            {
                "title": "How are you?",
                "prompt": "How are you?",
                "response": "I'm fine, thank you!",
                "practice_keywords": ["how are you doing", "how's everything", "how is it going"],
            },
            {
                "title": "Do you like red or yellow?",
                "prompt": "Do you like red or yellow?",
                "response": "I like red.",
                "practice_keywords": ["pink or purple", "blue or green", "orange or green"],
            },
            {
                "title": "I must go now.",
                "prompt": "I must go now.",
                "response": "Okay. See you!",
                "practice_keywords": ["leave now", "take care", "see you tomorrow"],
            },
            {
                "title": "Can we go under the tree?",
                "prompt": "Can we go under the tree?",
                "response": "Yes, it's cool there.",
                "practice_keywords": ["inside the library", "inside the house", "outside"],
            },
            {
                "title": "We are friends, right?",
                "prompt": "We are friends, right?",
                "response": "Yes, we are.",
                "practice_keywords": ["best friends", "classmates", "same team"],
            },
            {
                "title": "Why are you sad?",
                "prompt": "Why are you sad?",
                "response": "Because I lost my toy.",
                "practice_keywords": ["bored", "excited", "sleepy"],
            },
            {
                "title": "English Village was fun!",
                "prompt": "English Village was fun!",
                "response": "Yes! I learned many new words.",
                "practice_keywords": ["excited", "memorable", "helpful"],
            },
            {
                "title": "Should we come again?",
                "prompt": "Should we come again?",
                "response": "Yes! Let's come again next year.",
                "practice_keywords": ["visit again", "we should come again", "definitely"],
            },
        ],
    },
}
